serviceSample = [
    "Bọc răng sứ là gì?",
    "Trường hợp nên bọc răng sứ?",
    "Bọc răng sứ có tốt không?",
    "Các dáng răng sứ được nhiều khách hàng chọn làm",
    "Quy trình bọc răng sứ thẩm mỹ",
    "Bọc răng sứ giá bao nhiêu?",
    "Tại sao phải bọc răng sứ thẩm mỹ",
    "Đội ngũ bác sĩ của My Auris",
    "Đánh giá khách hàng sau khi làm răng sứ tại Nha Khoa My Auris",
    "Bọc răng sứ răng hàm nên chọn loại nào?",
    "Bọc răng sứ tại My Auris có thanh toán trả góp được không?",
    "Răng sứ lâu năm bị đau nhức là do đâu?",
    "Bọc răng sứ có bị hôi miệng không?",
    "Bọc răng sứ có lấy tủy không?",
    "Cảm giác sau khi bọc răng sứ như thế nào?",
    "Vôi răng là gì?",
    "Tác hại của vôi răng",
    "Phòng ngừa vôi răng đúng cách",
    "Tác dụng của việc cạo vôi răng",
    "Qui trình làm sạch răng tại My Auris với công nghệ tiên tiến nhất",
    "Cầu răng sứ là gì?",
    "Những nguy cơ khi bị mất răng",
    "Giải pháp cầu răng sứ",
    "Ưu điểm của phương pháp bắc cầu răng sứ",
    "Quy trình bắc cầu răng sứ tại My Auris",
    "Vì sao nên chọn My Auris",
    "Dán răng sứ là gì?",
    "Những ưu điểm của mặt dán răng sứ",
    "Trường hợp nào nên dán răng sứ",
    "Trường hợp nào không nên dán răng sứ",
    "Quy trình dán răng sứ tại Nha khoa My Auris",
    "Dán sứ veneer có gì khác với bọc răng sứ truyền thống",
    "Điều trị tủy an toàn bằng công nghệ mới tại My Auris",
    "Nguyên nhân của viêm tủy răng?",
    "Tác dụng của điều trị tủy răng",
    "Quy trình điều trị tủy răng an toàn tại Viện Công nghệ Nha khoa My Auris",
    "Nhổ răng là gì?",
    "Nhổ răng có đau không?",
    "Tác dụng của nhổ răng khi răng bị tổn thương",
    "Nhổ răng An toàn- Không đau",
    "Niềng Răng Thẩm Mỹ Là Gì?",
    "Khi Nào Nên Niềng RăngCho Người Lớn?",
    "Những Trường Hợp Nên Niềng Răng Sớm",
    "Ưu Điểm Sau Khi Niềng Răng",
    "Niềng Răng Sau 25 – 30 Tuổi Có Hiệu Quả Không?",
    "Quy Trình Niềng Răng",
    "Thời gian niềng răng mất bao lâu?",
    "Các Loại Niềng Răng Thẩm Mỹ",
    "Bác Sĩ Chỉnh Nha Giàu Kinh Nghiệm",
    "Vì Sao Nên Lựa Chọn Niềng Răng Tại Nha Khoa My Auris",
    "Chi Phí Niềng Răng Tại Nha Khoa My Auris",
    "Những Lưu Ý Quan Trọng Giúp Niềng Răng Thành Công",
    "Niềng răng có đau không?",
    "Niềng răng có cần nhổ răng không?",
    "Có thể niềng răng tại nhà không?",
    "Niềng răng cho người lớn khác gì so với niềng răng trẻ em?",
    "Làm sao để rút ngắn thời gian niềng răng?",
    "Niềng răng có ảnh hưởng đến khả năng phát âm không?",
    "Chế độ ăn uống khi niềng răng thay đổi như thế nào?",
    "Phủ răng sứ là gì?",
    "So sánh giữa Bọc răng sứ và Phủ răng sứ",
    "Chi phí phủ răng sứ là bao nhiêu?",
    "Nên phủ răng sứ ở đâu?",
    "Trám răng là gì?",
    "Các trường hợp nên Trám Răng",
    "Khi Trám Răng cần lưu ý những gì?",
    "Qui trình trám răng tại My Auris với công nghệ tiên tiến nhất",
    "Cấu Tạo Răng ImplantGồm Bao Nhiêu Bộ Phận",
    "Đối Tượng Nào Nên Trồng Răng Implant?",
    "Quy Trình Cấy Ghép Implant Chuẩn Y Khoa",
    "Các Phương Pháp Trồng Răng Implant",
    "Cấy Ghép Implant Chi Phí Bao Nhiêu?",
    "Vì Sao Giá Làm Răng Implant Trên Thị Trường Khác Nhau?",
    "Những Lưu Ý Giúp Cấy Ghép Implant Thành Công",
    "Trồng răng Implant có đau không?",
    "Phương pháp trồng răng Implant có hạn chế gì không?",
    "Độ tuổi trồng răng Implant tốt nhất là bao nhiêu?",
    "Trồng răng Implant bao lâu thì lành vết thương?",
    "Vì sao trồng răng Implant có giá thành cao?"
]


chitchatSample = [
    "Xin chào, ở đây có ai không?",
    "Bạn là AI thật đó hả?",
    "Bạn nói chuyện như người thật luôn á!",
    "Bạn có mệt không khi tư vấn hoài vậy?",
    "Bạn có tên không? Cho mình gọi dễ hơn nha!",
    "Tư vấn giúp mình theo cách nhẹ nhàng nha, mình hơi sợ nha sĩ"
]

