dinh_nghia:
  - "là gì"
  - "cầu răng sứ là gì"
  - "trám răng là gì"
  - "niềng răng là gì"
  - "cầu răng sứ"

chi_phi:
  - "giá bao nhiêu"
  - "chi phí"
  - "tốn bao nhiêu"
  - "giá cả"
  - "bao nhiêu tiền"
  - "giá thành"
  - "trả góp"

quy_trinh:
  - "quy trình"
  - "các bước"
  - "thực hiện như thế nào"
  - "qui trình"

dieu_kien_ap_dung:
  - "trường hợp nào"
  - "nên"
  - "không nên"
  - "ai phù hợp"
  - "độ tuổi"

loi_ich:
  - "tốt không"
  - "ưu điểm"
  - "lợi ích"
  - "bền không"
  - "hiệu quả không"
  - "tác dụng"

tac_dung_phu:
  - "đau không"
  - "hôi miệng"
  - "tác hại"
  - "biến chứng"
  - "nguy cơ"

so_sanh:
  - "khác gì"
  - "so sánh"
  - "khác nhau"
  - "có gì khác"

cham_soc:
  - "chăm sóc"
  - "cảm giác sau khi"
  - "sau khi làm"
  - "chế độ ăn uống"
  - "lưu ý"

ly_do_chon:
  - "tại sao nên chọn"
  - "lý do chọn"
  - "vì sao chọn"
  - "tại sao phải"

thong_tin_bac_si:
  - "bác sĩ"
  - "đội ngũ"
  - "chuyên gia"

phan_hoi_khac_hang:
  - "đánh giá khách hàng"
  - "phản hồi"
  - "trải nghiệm khách hàng"

truong_hop_cu_the:
  - "răng hàm"
  - "trường hợp cụ thể"
  - "loại nào phù hợp"

thoi_gian:
  - "bao lâu"
  - "thời gian"
